# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField()),
                ('inc', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Вес за день',
                'verbose_name_plural': 'Веса',
            },
        ),
    ]
