# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
